name: Deploy the app to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: ğŸ—ï¸ Build on Node.js 24.x
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ‘¯â€â™‚ï¸ Clone repository
        uses: actions/checkout@v4
      - name: ğŸ”§ Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: ğŸ“¥ Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ğŸ“‘ Generate JSDoc documentation
        run: pnpm jsdoc
      - name: ğŸ§° Build
        id: build
        run: pnpm run build --if-present
      - name: ğŸ—’ï¸ Build report
        if: always()
        run: |
          echo "Node.js version: $(node -v)"
          if [[ ${{ steps.build.outcome }} == "success" ]]; then
            echo "âœ… Build succeeded"
          else
            echo "âŒ Build failed"
          fi
      - name: ğŸ”§ Setup pages
        id: pages
        uses: actions/configure-pages@v3
      - name: ğŸ“¤ Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: ğŸš€ Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: [build]
    steps:
      - name: ğŸš€ Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
