name: Pull request CI

on:
  pull_request:
    types: [reopened, opened, synchronize, ready_for_review]
    branches: ["*", "**/*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘¯â€â™‚ï¸ Clone repository
        uses: actions/checkout@v3
      - name: ğŸ”§ Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: ğŸ” Enable Corepack
        run: corepack enable
        shell: bash

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile
      - name: ğŸ‘®ğŸ»â€â™‚ï¸ Run lint
        id: lint
        run: pnpm lint:ci
